# NumPy exercises

In [1]:
#import the Numpy package
import numpy as np

In [2]:
#Set the random seed
np.random.seed(859)

In [3]:
#Create a random array of 100 values between 0 and 1
arr_1 = np.linspace(0,1,100)

#Display the resulting array
arr_1

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [4]:
#Report the shape of the resulting array
arr_1.shape

(100,)

In [5]:
#Report the data type of the resulting array
arr_1.dtype

dtype('float64')

In [6]:
#Remote the mean value of all values in your array
arr_1.mean()

0.5

In [8]:
#Multiply each value in your array to get values between 0 and 100, saving the results as "arr_2"
arr_2 = arr_1 * 100

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [9]:
#Reshape the array above to be 25 rows and 4 columns, saving the result as "arr_3"
arr_3 = arr_2.reshape(25,4)

In [19]:
#Show the 3rd row of this array
print(arr_3[4])

[16.16161616 17.17171717 18.18181818 19.19191919]


In [17]:
#Show the values in the 2nd column of this array
print(arr_3[:,3])

[  3.03030303   7.07070707  11.11111111  15.15151515  19.19191919
  23.23232323  27.27272727  31.31313131  35.35353535  39.39393939
  43.43434343  47.47474747  51.51515152  55.55555556  59.5959596
  63.63636364  67.67676768  71.71717172  75.75757576  79.7979798
  83.83838384  87.87878788  91.91919192  95.95959596 100.        ]


In [20]:
#Show the mean of the values in the 2nd column
arr_3[:,3].mean()

51.51515151515152